package net.chriskatze.katzencraft.entity.client.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class CaterpieAnimations {

    // IDLE ------------------------------------------------------------------------------------------------------------

    public static final Animation CATERPIE_GROUND_IDLE = Animation.Builder.create(1f).looping()
            .addBoneAnimation("body_segment2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.01f, -0.05f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 0.04f, -0.08f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0f, 0.06f, -0.09f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.09f, -0.1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0.1f, -0.09f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41676663f, AnimationHelper.createTranslationalVector(0f, 0.1f, -0.08f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.49999999999999994f, AnimationHelper.createTranslationalVector(0f, 0.09f, -0.05f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createTranslationalVector(0f, 0.06f, -0.03f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 0.04f, -0.01f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0.01f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0f, 0f, -0.01f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167667f, AnimationHelper.createTranslationalVector(0f, 0f, -0.02f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.01f, -0.05f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 0.19f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0f, 0.15f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41676663f, AnimationHelper.createTranslationalVector(0f, 0.01f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.49999999999999994f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createTranslationalVector(0f, 0.01f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0f, 0.15f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167667f, AnimationHelper.createTranslationalVector(0f, 0.19f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-12f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(-13f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(-13.73f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(-14f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(-13.73f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41676663f, AnimationHelper.createRotationalVector(-13f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.49999999999999994f, AnimationHelper.createRotationalVector(-12f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createRotationalVector(-11f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createRotationalVector(-10.27f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createRotationalVector(-10.27f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167667f, AnimationHelper.createRotationalVector(-11f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-12f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(7f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(8f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(8.73f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(9f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(8.73f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41676663f, AnimationHelper.createRotationalVector(8f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.49999999999999994f, AnimationHelper.createRotationalVector(7f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createRotationalVector(6f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createRotationalVector(5.27f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createRotationalVector(5.27f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167667f, AnimationHelper.createRotationalVector(6f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(7f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail3",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(6f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(6.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(6.87f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(7f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(6.87f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41676663f, AnimationHelper.createRotationalVector(6.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.49999999999999994f, AnimationHelper.createRotationalVector(6f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createRotationalVector(5.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createRotationalVector(5.13f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createRotationalVector(5.13f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167667f, AnimationHelper.createRotationalVector(5.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(6f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 0.03f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0f, 0.04f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0.04f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41676663f, AnimationHelper.createTranslationalVector(0f, 0.03f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.49999999999999994f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createTranslationalVector(0f, -0.02f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, -0.04f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0f, -0.04f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167667f, AnimationHelper.createTranslationalVector(0f, -0.03f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail4",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41676663f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.49999999999999994f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167667f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();

    // WALK ------------------------------------------------------------------------------------------------------------

    public static final Animation CATERPIE_GROUND_WALK = Animation.Builder.create(1f).looping()
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.87f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, 0.41f, -0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0.11f, -0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createTranslationalVector(0f, 0.22f, -0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0.25f, -0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.18f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0.04f, -0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, 0.21f, -0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createTranslationalVector(0f, 0.74f, -0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createTranslationalVector(0f, 0.99f, -0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.87f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(4.31f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(7.61f, 0f, 0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(9.76f, 0f, 0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createRotationalVector(9.76f, 0f, -0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(7.94f, 0f, -0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(3.24f, 0f, 0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(1.98f, 0f, 0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createRotationalVector(1.55f, 0f, -0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createRotationalVector(2.44f, 0f, -0.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(4.31f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.71f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, -0.16f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, -0.45f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createTranslationalVector(0f, -0.89f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createTranslationalVector(0f, -0.99f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.71f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body_segment",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.71f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, -0.16f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0.45f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createTranslationalVector(0f, 0.89f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0.99f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.71f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0.16f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, -0.45f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createTranslationalVector(0f, -0.89f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createTranslationalVector(0f, -0.99f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.71f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body_segment",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(3.46f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(1.63f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-4.16f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createRotationalVector(-14.86f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-19.89f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-17.32f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-8.13f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(0.83f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createRotationalVector(2.97f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createRotationalVector(3.98f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(3.46f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body_segment2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, -0.18f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, -0.29f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createTranslationalVector(0f, -0.29f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, -0.18f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0.46f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, 0.49f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createTranslationalVector(0f, 0.33f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createTranslationalVector(0f, 0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body_segment2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-31.42f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(-28.28f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-14.34f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createRotationalVector(5.08f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(14.42f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(14.1f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(8.39f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(-0.52f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createRotationalVector(-9.23f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createRotationalVector(-22.55f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-31.42f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 1.38f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(11.11f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(4.06f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-20.74f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.65f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(-24.74f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(-17.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(0.47f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(-2.27f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-22.25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(-37.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-9.63f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.65f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(0.35f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(15.63f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail3",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, 0f, -0.1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, -0.67f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createTranslationalVector(0f, 0f, -0.98f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0f, -0.91f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, -0.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.55f, AnimationHelper.createTranslationalVector(0f, 0f, -0.21f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.65f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, 0.38f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createTranslationalVector(0f, 0.13f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.85f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail3",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(14.72f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(27.96f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(32.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createRotationalVector(33.35f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(22.96f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.65f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(19.97f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(0.94f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail4",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.1f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.30000000000000004f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7999999999999999f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8999999999999999f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(67.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
}
